[package]
name = "slime-rs"
version = "0.0.1"
authors = ["abb128"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
deku = "0.12.3"